sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - "~/.m2/repository"

before_script:
  - "./travis/install-dependencies.sh"
script:
  - mvn clean install -DskipTests
after_success:
  - "./travis/after_script.sh"

before_deploy:
  - "./travis/before_deploy.sh"
deploy:
  provider: script
  script: ./travis/deploy.sh
  on:
    all_branches: true

