sudo: required
language: java
jdk:
  - oraclejdk8

before_script: ./install-dependencies.sh
script:
  - mvn clean install -DskipTests
before_cache:
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: