sudo: false

language: java
jdk:
  - oraclejdk8

services:
  - docker

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.cache/yarn

before_install:
  - ".travis/install-dependencies.sh"
install: true

script:
  - mvn clean install -DskipTests
after_success:
  - ".travis/after_script.sh"

before_deploy:
  - ".travis/before_deploy.sh"
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true

