sudo: false

language: java
jdk:
  - oraclejdk8

services:
  - docker

env:
  - NODE_VERSION="10.15.0"

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.cache/yarn

before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
install: true

before_script:
  - ".travis/install-dependencies.sh"
script:
  - mvn clean install -DskipTests
after_success:
  - ".travis/install_web_distribution.sh"

before_deploy:
  - ".travis/install_openshift_distribution.sh"
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true

